#!/bin/bash

# Script to demonstrate Claude Code integration for chapter generation
# This is a conceptual example of how Claude Code could be used to generate chapters

# Usage: ./generate-chapter.sh <module-name> <chapter-title> <output-path>

MODULE_NAME=$1
CHAPTER_TITLE=$2
OUTPUT_PATH=$3

if [ -z "$MODULE_NAME" ] || [ -z "$CHAPTER_TITLE" ] || [ -z "$OUTPUT_PATH" ]; then
    echo "Usage: $0 <module-name> <chapter-title> <output-path>"
    echo "Example: $0 module1-ros 'Advanced ROS 2 Concepts' ./docs/module1-ros/advanced-concepts.md"
    exit 1
fi

# Create the chapter file with a template
cat > "$OUTPUT_PATH" << EOF
---
sidebar_position: 2
---

# $CHAPTER_TITLE

## Overview

This chapter covers the key concepts related to $CHAPTER_TITLE in the context of $MODULE_NAME.

## Learning Objectives

After completing this chapter, you will be able to:
- Understand the fundamental concepts of $CHAPTER_TITLE
- Apply these concepts in practical scenarios
- Integrate with other components in the system

## Content

[Chapter content would be generated by Claude Code based on context and requirements]

## Summary

This chapter has covered the essential aspects of $CHAPTER_TITLE. The concepts learned here will be applied in subsequent chapters and modules.

## Exercises

1. [Exercise 1 related to the content]
2. [Exercise 2 related to the content]
3. [Exercise 3 related to the content]
EOF

echo "Chapter '$CHAPTER_TITLE' created at $OUTPUT_PATH"
echo "Note: This is a template. In a real implementation, Claude Code would generate the detailed content."